apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    app: rabbitmq
  name: rabbitmq-rules
spec:
  groups:
    - name: "rabbitmq alerts"
      rules:
        - alert: RabbitmqExporterScrapeFailed
          expr: up{job="rabbitmq-metrics"} != 1
          labels:
            severity: critical
          annotations:
            summary: 'Pod: {{ $labels.pod }}'
            description: 'Fix Rabbitmq metrics scape for pod: {{ $labels.pod }}'

        - alert: RabbitmqNoMetrics
          expr: absent(rabbitmq_up{job="rabbitmq-metrics"}) == 1
          labels:
            severity: warning
          annotations:
            summary: 'No metrics from Rabbitmq instances'
            description: 'Fix Rabbitmq metrics scape. Job: {{ $labels.job }}'

        - alert: RabbitmqMetricsScrapeFailed
          expr: rabbitmq_up != 1
          labels:
            severity: critical
          annotations:
            summary: 'No metrics from Rabbitmq'
            description: 'Rabbitmq-exporter unable to scrape metrics from Rabbitmq endpoint. Check logs of exporter and Rabbitmq.'
