apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: alertmanager-rancher-monitoring-alertmanager-custom
data:
  alertmanager.yaml: >{{ .Files.Get "my_config" | b64enc | nindent 4 }}
  rancher_defaults.tmpl: >{{ .Files.Get "my_template" | b64enc | nindent 4 }}
