{
 "title": "Cloudwatch RDS",
 "description": "Visualize OS metrics for Amazon RDS instance",
 "tags": [
  "cloudwatch",
  "db",
  "mysql",
  "prometheus"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "data_source", "label": "Data source", "query": "prometheus" },
   {
    "name": "db_instance",
    "label": "DB Instance",
    "query": {
     "query": "label_values(aws_rds_cpuutilization_average, dbinstance_identifier)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Exporter statuses",
   "type": "graph",
   "description": "Up is 1\nDown is 0",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "up{instance=~\".*:9106\"}",
     "legendFormat": "{{instance}} - Exporter status"
    },
    {
     "expr": "pg_up{dbinstance_identifier=~\"$db_instance\"}",
     "legendFormat": "{{instance}} - Scrape status"
    },
    {
     "expr": "up{instance=~\".*:9187\"}",
     "legendFormat": "{{instance}} - Exporter status"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 }, "repeat": "instance" },
  {
   "title": "CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "CPU",
     "dimensions": { "DBInstanceIdentifier": "$instance" },
     "expr": "aws_rds_cpuutilization_average{dbinstance_identifier=~\"$db_instance\"}",
     "legendFormat": "{{ dbinstance_identifier }}",
     "metricName": "CPUUtilization",
     "namespace": "AWS/RDS",
     "period": "60",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "CPU Credit Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "Credits Accumulated",
     "dimensions": { "DBInstanceIdentifier": "$instance" },
     "expr": "aws_rds_cpucredit_usage_average{dbinstance_identifier=~\"$db_instance\"}",
     "legendFormat": "{{ dbinstance_identifier }}",
     "metricName": "CPUCreditBalance",
     "namespace": "AWS/RDS",
     "period": "300",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "repeat": "instance",
   "collapsed": true,
   "panels": [
    {
     "title": "Free Storage Space",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "Available",
       "dimensions": { "DBInstanceIdentifier": "$instance" },
       "expr": "aws_rds_free_storage_space_average{dbinstance_identifier=~\"$db_instance\"}",
       "legendFormat": "{{ dbinstance_identifier }}",
       "metricName": "FreeStorageSpace",
       "namespace": "AWS/RDS",
       "period": "60",
       "region": "$region",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "Disk Operations",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "alias": "Read",
       "dimensions": { "DBInstanceIdentifier": "$instance" },
       "expr": "aws_rds_write_iops_average{dbinstance_identifier=~\"$db_instance\"}",
       "legendFormat": "{{ dbinstance_identifier }} Write",
       "metricName": "ReadIOPS",
       "namespace": "AWS/RDS",
       "period": "60",
       "region": "$region",
       "statistic": "Average"
      },
      {
       "expr": "aws_rds_read_iops_average{dbinstance_identifier=~\"$db_instance\"}",
       "legendFormat": "{{ dbinstance_identifier }} Read"
      }
     ]
    },
    {
     "title": "Disk Queue Depth",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 35 },
     "repeat": "instance",
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "Outstanding IO Requests",
       "dimensions": { "DBInstanceIdentifier": "$instance" },
       "expr": "aws_rds_disk_queue_depth_average{dbinstance_identifier=~\"$db_instance\"}",
       "legendFormat": "{{ dbinstance_identifier }}",
       "metricName": "DiskQueueDepth",
       "namespace": "AWS/RDS",
       "period": "60",
       "region": "$region",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "Disk Latency",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "alias": "Read",
       "dimensions": { "DBInstanceIdentifier": "$instance" },
       "expr": "aws_rds_write_latency_average{dbinstance_identifier=~\"$db_instance\"}",
       "legendFormat": "{{ dbinstance_identifier }} Write",
       "metricName": "ReadLatency",
       "namespace": "AWS/RDS",
       "period": "60",
       "region": "$region",
       "statistic": "Average"
      },
      {
       "expr": "aws_rds_read_latency_average{dbinstance_identifier=~\"$db_instance\"}",
       "legendFormat": "{{ dbinstance_identifier }} Read"
      }
     ]
    },
    {
     "title": "Disk Throughput",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "Inbound",
       "dimensions": { "DBInstanceIdentifier": "$instance" },
       "expr": "aws_rds_write_throughput_average{dbinstance_identifier=~\"$db_instance\"}",
       "legendFormat": "{{ dbinstance_identifier }} Transmit",
       "metricName": "NetworkReceiveThroughput",
       "namespace": "AWS/RDS",
       "period": "60",
       "region": "$region",
       "statistics": [ "Average" ]
      },
      {
       "alias": "Outbound",
       "dimensions": { "DBInstanceIdentifier": "$instance" },
       "expr": "aws_rds_read_throughput_average{dbinstance_identifier=~\"$db_instance\"}",
       "legendFormat": "{{ dbinstance_identifier }} Receive",
       "metricName": "NetworkTransmitThroughput",
       "namespace": "AWS/RDS",
       "period": "60",
       "region": "$region",
       "statistics": [ "Average" ]
      }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "repeat": "instance",
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Free",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 55 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "Available",
       "dimensions": { "DBInstanceIdentifier": "$instance" },
       "expr": "aws_rds_freeable_memory_average{dbinstance_identifier=~\"$db_instance\"}",
       "legendFormat": "{{ dbinstance_identifier }}",
       "metricName": "FreeableMemory",
       "namespace": "AWS/RDS",
       "period": "60",
       "region": "$region",
       "statistics": [ "Average" ]
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "repeat": "instance",
   "collapsed": true,
   "panels": [
    {
     "title": "Network",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 62 },
     "repeat": "instance",
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "alias": "Inbound",
       "dimensions": { "DBInstanceIdentifier": "$instance" },
       "expr": "aws_rds_network_transmit_throughput_average{dbinstance_identifier=~\"$db_instance\"}",
       "legendFormat": "{{ dbinstance_identifier }} Transmit",
       "metricName": "NetworkReceiveThroughput",
       "namespace": "AWS/RDS",
       "period": "60",
       "region": "$region",
       "statistics": [ "Average" ]
      },
      {
       "alias": "Outbound",
       "dimensions": { "DBInstanceIdentifier": "$instance" },
       "expr": "aws_rds_network_receive_throughput_average{dbinstance_identifier=~\"$db_instance\"}",
       "legendFormat": "{{ dbinstance_identifier }} Receive",
       "metricName": "NetworkTransmitThroughput",
       "namespace": "AWS/RDS",
       "period": "60",
       "region": "$region",
       "statistics": [ "Average" ]
      }
     ]
    }
   ]
  },
  {
   "title": "Connections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Database connections",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 70 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "aws_rds_database_connections_average{dbinstance_identifier=~\"$db_instance\"}",
       "legendFormat": "{{ dbinstance_identifier }}"
      }
     ]
    }
   ]
  }
 ]
}