{
 "title": "Loki stack",
 "description": "This dashboard can be used to detect issues on the Loki stack, when deployed in Kubernetes. Shows: some error metrics published by Promtail/Loki. Error and warning logs emitted by Promtail/Loki. Memory and CPU usage of Promtail/Loki compared against the Kubernetes memory/cpu limits and requests.",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "prom_datasource", "label": "Datasource prom", "query": "prometheus" },
   { "name": "loki_datasource", "label": "Datasource loki", "query": "loki" }
  ]
 },
 "panels": [
  { "title": "Problems in the Loki Stack", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of error/warning messages logged by Loki itself",
   "type": "graph",
   "description": "Total number of messages logged by Loki itself",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(rate(loki_log_messages_total{level=~\"error|warn\"}[1m])) by (level)\n",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "Error/warning messages logged by Loki itself",
   "type": "logs",
   "gridPos": { "h": 5, "w": 15, "x": 9, "y": 1 },
   "targets": [
    {
     "expr": "{app=~\"loki.*\"} | logfmt | level=\"warn\" or level=\"error\""
    }
   ]
  },
  {
   "title": "Error/warning messages logged by Promtail",
   "type": "graph",
   "description": "Total number of messages logged by Promtail",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(count_over_time({app=\"promtail\"} | logfmt | level=\"warn\" [1m]))",
     "legendFormat": "Warn"
    },
    {
     "expr": "sum(count_over_time({app=\"promtail\"} | logfmt | level=\"error\" [1m]))",
     "legendFormat": "Error"
    }
   ]
  },
  {
   "title": "Error/warning messages logged by Promtail",
   "type": "logs",
   "gridPos": { "h": 5, "w": 15, "x": 9, "y": 6 },
   "targets": [
    {
     "expr": "{app=\"promtail\"} | logfmt | level=\"warn\" or level=\"error\""
    }
   ]
  },
  {
   "title": "Promtail - dropped log entries",
   "type": "graph",
   "description": "Number of log entries dropped because failed to be sent to the Loki ingester after all retries.",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(promtail_dropped_entries_total[1m])*60",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Logging activity",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of Streams in Loki",
     "type": "graph",
     "description": "The total number of streams created per tenant.\nThis should not increase after startup.",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "loki_ingester_memory_streams", "legendFormat": "Streams" }
     ]
    },
    {
     "title": "Loki (distributor) - log entries received per second",
     "type": "graph",
     "description": "The total number of log entries received per tenant (not necessarily of lines, as an entry can have more than one line of text).",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(loki_distributor_lines_received_total[1m])"
      }
     ]
    },
    {
     "title": "Bytes received in ingester per second",
     "type": "graph",
     "description": "The total number of uncompressed bytes received per tenant.\n",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(rate(loki_distributor_bytes_received_total[1m]))"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Loki memory usage (% of Kubernetes memory limit)",
     "type": "graph",
     "description": "Percentage of actual usage over configured limit",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "100 * max by(pod,container) (container_memory_working_set_bytes{container!=\"\",container!=\"POD\",pod=~\"loki.*\"})\n/\non (pod,container) group_left kube_pod_container_resource_limits{resource=\"memory\",pod=~\"loki.*\"}",
       "legendFormat": "{{pod}} / {{container}}"
      }
     ]
    },
    {
     "title": "Loki memory usage vs Kubernetes limit and request",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "container_memory_working_set_bytes{container!=\"\",container!=\"POD\",pod=~\"loki.*\"}",
       "legendFormat": "{{pod}} / {{container}}"
      },
      {
       "expr": "min(kube_pod_container_resource_limits{resource=\"memory\",pod=~\"loki.*\"})",
       "legendFormat": "Limit"
      },
      {
       "expr": "min(kube_pod_container_resource_requests{resource=\"memory\",pod=~\"loki.*\"})",
       "legendFormat": "Request"
      }
     ]
    },
    {
     "title": "Promtail memory usage (% of Kubernetes memory limit)",
     "type": "graph",
     "description": "Percentage of actual usage over configured limit",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "100* max by(pod,container) (container_memory_working_set_bytes{container!=\"\",container!=\"POD\",pod=~\"promtail.*\"})\n/\non (pod,container) (kube_pod_container_resource_limits{resource=\"memory\",pod=~\"promtail.*\"})",
       "legendFormat": "{{pod}} / {{container}}"
      }
     ]
    },
    {
     "title": "Promtail memory usage vs Kubernetes limit and request",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "container_memory_working_set_bytes{container!=\"\",container!=\"POD\",pod=~\"promtail.*\"}",
       "legendFormat": "{{pod}} / {{container}}"
      },
      {
       "expr": "min(kube_pod_container_resource_limits{resource=\"memory\",pod=~\"promtail.*\"})",
       "legendFormat": "Limit"
      },
      {
       "expr": "min(kube_pod_container_resource_limits{resource=\"memory\",pod=~\"promtail.*\"})",
       "legendFormat": "Request"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Loki CPU usage (% of Kubernetes CPU limit)",
     "type": "graph",
     "description": "percentage of configured limit",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 43 },
     "yaxes": [
      { "format": "percent", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "100* rate(container_cpu_usage_seconds_total{container!=\"POD\",container!=\"\",pod=~\"loki.*\"}[1m])\n/\non (pod,container) kube_pod_container_resource_limits{resource=\"cpu\",pod=~\"loki.*\"}",
       "legendFormat": "{{pod}} / {{container}}"
      }
     ]
    },
    {
     "title": "Loki CPU usage vs Kubernetes limit and request",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 49 },
     "yaxes": [
      { "format": "none", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "rate(container_cpu_usage_seconds_total{container!=\"\",container!=\"POD\",pod=~\"loki.*\"}[1m])",
       "legendFormat": "{{pod}} / {{container}}"
      },
      {
       "expr": "min(kube_pod_container_resource_limits{resource=\"cpu\",pod=~\"loki.*\"})",
       "legendFormat": "CPU Limit"
      },
      {
       "expr": "min(kube_pod_container_resource_limits{resource=\"cpu\",pod=~\"loki.*\"})",
       "legendFormat": "CPU Request"
      }
     ]
    },
    {
     "title": "Promtail CPU usage (% of Kubernetes limit)",
     "type": "graph",
     "description": "percentage of configured limit",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 55 },
     "yaxes": [
      { "format": "percent", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "100 * rate(container_cpu_usage_seconds_total{container!=\"\",container!=\"POD\",pod=~\"promtail.*\"}[1m])\n/\non (pod,container) kube_pod_container_resource_limits{resource=\"cpu\",pod=~\"promtail.*\"}",
       "legendFormat": "{{pod}} / {{container}}"
      }
     ]
    },
    {
     "title": "Promtail CPU usage vs Kubernetes limit and request",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 61 },
     "yaxes": [
      { "format": "none", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "rate(container_cpu_usage_seconds_total{container!=\"\",container!=\"POD\",pod=~\"promtail.*\"}[1m])",
       "legendFormat": "{{pod}} / {{container}}"
      },
      {
       "expr": "min(kube_pod_container_resource_limits{resource=\"cpu\",pod=~\"promtail.*\"})",
       "legendFormat": "CPU Limit"
      },
      {
       "expr": "min(kube_pod_container_resource_limits{resource=\"cpu\",pod=~\"promtail.*\"})",
       "legendFormat": "CPU Request"
      }
     ]
    }
   ]
  }
 ]
}