{
 "title": "Prometheus metrics",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "data_source", "label": "Data source", "query": "prometheus" },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(prometheus_config_last_reload_successful,instance)"
   },
   {
    "name": "reason",
    "label": "Reason",
    "query": "label_values(net_conntrack_dialer_conn_failed_total,reason)"
   },
   {
    "name": "dialer_name",
    "label": "Dialer name",
    "query": "label_values(net_conntrack_dialer_conn_failed_total,dialer_name)"
   },
   {
    "name": "limit",
    "query": "1,2,3,4,5,6,7,8,9,10,15,20,25,30,40,50,70,100,9999"
   }
  ]
 },
 "panels": [
  { "title": "Exporter", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Prometheus scrape status (bottom $limit)",
   "type": "graph",
   "description": "OK = 1",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "bottomk($limit, up{instance=~\"$instance\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Reload success (bottom $limit)",
   "type": "graph",
   "description": "OK = 1",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "bottomk($limit, prometheus_config_last_reload_successful{instance=~\"$instance\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Connections failed (top $limit)",
   "type": "graph",
   "description": "OK = 0",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk($limit, delta(net_conntrack_dialer_conn_failed_total{instance=~\"$instance\",dialer_name=~\"$dialer_name\",reason=~\"$reason\"}[5m]))",
     "legendFormat": "{{instance}} {{reason}} {{dialer_name}}"
    }
   ]
  },
  {
   "title": "Notifications dropped (top $limit)",
   "type": "graph",
   "description": "Total number of alerts dropped due to errors when sending to Alertmanager",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk($limit, delta(prometheus_notifications_dropped_total{instance=~\"$instance\"}[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}