{
 "title": "Request Handling Performance",
 "tags": [ "nginx" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "data_source", "label": "Data source", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(nginx_ingress_controller_config_hash, controller_namespace)"
   },
   {
    "name": "controller_class",
    "label": "Controller Class",
    "query": "label_values(nginx_ingress_controller_config_hash{namespace=~\"$namespace\"}, controller_class)"
   },
   {
    "name": "controller",
    "label": "Controller",
    "query": "label_values(nginx_ingress_controller_config_hash{namespace=~\"$namespace\",controller_class=~\"$controller_class\"}, controller_pod) "
   },
   {
    "name": "exported_namespace",
    "label": "Exported namespace",
    "query": "label_values(nginx_ingress_controller_request_duration_seconds_bucket{namespace=~\"$namespace\",controller_class=~\"$controller_class\",controller_pod=~\"$controller\"}, exported_namespace)"
   },
   {
    "name": "exported_service",
    "label": "Exported service",
    "query": "label_values(nginx_ingress_controller_request_duration_seconds_bucket{namespace=~\"$namespace\",controller_class=~\"$controller_class\",controller_pod=~\"$controller\",exported_namespace=~\"$exported_namespace\"}, exported_service)"
   },
   {
    "name": "ingress",
    "label": "Ingress",
    "query": "label_values(nginx_ingress_controller_requests{namespace=~\"$namespace\",controller_class=~\"$controller_class\",controller_pod=~\"$controller\",exported_namespace=~\"$exported_namespace\",exported_service=~\"$exported_service\"}, ingress) "
   },
   {
    "name": "method",
    "label": "Method",
    "query": "label_values(nginx_ingress_controller_request_duration_seconds_bucket{namespace=~\"$namespace\",controller_class=~\"$controller_class\",controller_pod=~\"$controller\",exported_namespace=~\"$exported_namespace\",exported_service=~\"$exported_service\"}, method) "
   },
   {
    "name": "path",
    "label": "Path",
    "query": "label_values(nginx_ingress_controller_request_duration_seconds_bucket{namespace=~\"$namespace\",controller_class=~\"$controller_class\",controller_pod=~\"$controller\",exported_namespace=~\"$exported_namespace\",exported_service=~\"$exported_service\"}, path) "
   },
   {
    "name": "status",
    "label": "Status",
    "query": "label_values(nginx_ingress_controller_request_duration_seconds_bucket{namespace=~\"$namespace\",controller_class=~\"$controller_class\",controller_pod=~\"$controller\",exported_namespace=~\"$exported_namespace\",exported_service=~\"$exported_service\"}, status) "
   }
  ]
 },
 "panels": [
  {
   "title": "Total request handling time",
   "type": "graph",
   "description": "Total time taken for nginx and upstream servers to process a request and send a response",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.5,\n  sum by (le)(\n    rate(\n      nginx_ingress_controller_request_duration_seconds_bucket{\nnamespace=~\"$namespace\",controller_class=~\"$controller_class\",controller_pod=~\"$controller\",exported_namespace=~\"$exported_namespace\",exported_service=~\"$exported_service\",ingress=~\"$ingress\",method=~\"$method\",path=~\"$path\",status=~\"$status\"\n      }[1m]\n    )\n  )\n)",
     "legendFormat": ".5"
    },
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum by (le)(\n    rate(\n    nginx_ingress_controller_request_duration_seconds_bucket{\nnamespace=~\"$namespace\",controller_class=~\"$controller_class\",controller_pod=~\"$controller\",exported_namespace=~\"$exported_namespace\",exported_service=~\"$exported_service\",ingress=~\"$ingress\",method=~\"$method\",path=~\"$path\",status=~\"$status\"\n      }[1m]\n    )\n  )\n)",
     "legendFormat": ".95"
    },
    {
     "expr": "histogram_quantile(\n  0.99,\n  sum by (le)(\n    rate(\n      nginx_ingress_controller_request_duration_seconds_bucket{\nnamespace=~\"$namespace\",controller_class=~\"$controller_class\",controller_pod=~\"$controller\",exported_namespace=~\"$exported_namespace\",exported_service=~\"$exported_service\",ingress=~\"$ingress\",method=~\"$method\",path=~\"$path\",status=~\"$status\"\n      }[1m]\n    )\n  )\n)",
     "legendFormat": ".99"
    }
   ]
  },
  {
   "title": "Upstream response time",
   "type": "graph",
   "description": "The time spent on receiving the response from the upstream server",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.5,\n  sum by (le)(\n    rate(\n      nginx_ingress_controller_response_duration_seconds_bucket{\nnamespace=~\"$namespace\",controller_class=~\"$controller_class\",controller_pod=~\"$controller\",exported_namespace=~\"$exported_namespace\",exported_service=~\"$exported_service\",ingress=~\"$ingress\",method=~\"$method\",path=~\"$path\",status=~\"$status\"\n      }[1m]\n    )\n  )\n)",
     "legendFormat": ".5"
    },
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum by (le)(\n    rate(\n    nginx_ingress_controller_response_duration_seconds_bucket{\nnamespace=~\"$namespace\",controller_class=~\"$controller_class\",controller_pod=~\"$controller\",exported_namespace=~\"$exported_namespace\",exported_service=~\"$exported_service\",ingress=~\"$ingress\",method=~\"$method\",path=~\"$path\",status=~\"$status\"\n      }[1m]\n    )\n  )\n)",
     "legendFormat": ".95"
    },
    {
     "expr": "histogram_quantile(\n  0.99,\n  sum by (le)(\n    rate(\n      nginx_ingress_controller_response_duration_seconds_bucket{\nnamespace=~\"$namespace\",controller_class=~\"$controller_class\",controller_pod=~\"$controller\",exported_namespace=~\"$exported_namespace\",exported_service=~\"$exported_service\",ingress=~\"$ingress\",method=~\"$method\",path=~\"$path\",status=~\"$status\"\n      }[1m]\n    )\n  )\n)",
     "legendFormat": ".99"
    }
   ]
  },
  {
   "title": "Request volume by Path",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "  sum by (path)(\n    rate(\n      nginx_ingress_controller_request_duration_seconds_count{\nnamespace=~\"$namespace\",controller_class=~\"$controller_class\",controller_pod=~\"$controller\",exported_namespace=~\"$exported_namespace\",exported_service=~\"$exported_service\",ingress=~\"$ingress\",method=~\"$method\",path=~\"$path\",status=~\"$status\"\n      }[1m]\n    )\n  )\n",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "Median upstream response time by Path",
   "type": "graph",
   "description": "For each path observed, its median upstream response time",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(\n  .5,\n  sum by (le, path)(\n    rate(\n      nginx_ingress_controller_response_duration_seconds_bucket{\nnamespace=~\"$namespace\",controller_class=~\"$controller_class\",controller_pod=~\"$controller\",exported_namespace=~\"$exported_namespace\",exported_service=~\"$exported_service\",ingress=~\"$ingress\",method=~\"$method\",path=~\"$path\",status=~\"$status\"\n      }[1m]\n    )\n  )\n)",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "Response error rate by Path",
   "type": "graph",
   "description": "Percentage of 4xx and 5xx responses among all responses.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (path) (rate(nginx_ingress_controller_request_duration_seconds_count{\nnamespace=~\"$namespace\",controller_class=~\"$controller_class\",controller_pod=~\"$controller\",exported_namespace=~\"$exported_namespace\",exported_service=~\"$exported_service\",ingress=~\"$ingress\",method=~\"$method\",path=~\"$path\",status =~ \"[4-5].*\"\n}[1m])) / sum by (path) (rate(nginx_ingress_controller_request_duration_seconds_count{\nnamespace=~\"$namespace\",controller_class=~\"$controller_class\",controller_pod=~\"$controller\",exported_namespace=~\"$exported_namespace\",exported_service=~\"$exported_service\",ingress=~\"$ingress\",method=~\"$method\",path=~\"$path\"\n}[1m]))",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "Upstream time consumed by Path",
   "type": "graph",
   "description": "For each path observed, the sum of upstream request time",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (path) (rate(nginx_ingress_controller_response_duration_seconds_sum{namespace=~\"$namespace\",controller_class=~\"$controller_class\",controller_pod=~\"$controller\",ingress=~\"$ingress\",method=~\"$method\",path=~\"$path\",status=~\"$status\"\n}[1m]))",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "Response error volume by Path",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "  sum (\n    rate(\n      nginx_ingress_controller_request_duration_seconds_count{\nnamespace=~\"$namespace\",controller_class=~\"$controller_class\",controller_pod=~\"$controller\",exported_namespace=~\"$exported_namespace\",exported_service=~\"$exported_service\",ingress=~\"$ingress\",method=~\"$method\",path=~\"$path\",status =~\"[4-5].*\",\n      }[1m]\n    )\n  ) by(path, status)\n",
     "legendFormat": "{{ path }} {{ status }}"
    }
   ]
  },
  {
   "title": "Average response size by Path",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum (\n  rate (\n      nginx_ingress_controller_response_size_sum {\nnamespace=~\"$namespace\",controller_class=~\"$controller_class\",controller_pod=~\"$controller\",exported_namespace=~\"$exported_namespace\",exported_service=~\"$exported_service\",ingress=~\"$ingress\",method=~\"$method\",path=~\"$path\",status=~\"$status\"\n      }[1m]\n  )\n)  by (path) / sum (\n  rate(\n      nginx_ingress_controller_response_size_count {\nnamespace=~\"$namespace\",controller_class=~\"$controller_class\",controller_pod=~\"$controller\",exported_namespace=~\"$exported_namespace\",exported_service=~\"$exported_service\",ingress=~\"$ingress\",method=~\"$method\",path=~\"$path\",status=~\"$status\"\n      }[1m]\n  )\n) by (path)\n",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "Upstream service latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum (\n  rate(\n      nginx_ingress_controller_ingress_upstream_latency_seconds_sum {\nnamespace=~\"$namespace\",controller_class=~\"$controller_class\",controller_pod=~\"$controller\",exported_namespace=~\"$exported_namespace\",exported_service=~\"$exported_service\",ingress=~\"$ingress\"\n      }[1m]\n)) / sum (\n  rate(\n      nginx_ingress_controller_ingress_upstream_latency_seconds_count {\nnamespace=~\"$namespace\",controller_class=~\"$controller_class\",controller_pod=~\"$controller\",exported_namespace=~\"$exported_namespace\",exported_service=~\"$exported_service\",ingress=~\"$ingress\"\n      }[1m]\n  )\n)\n",
     "legendFormat": "average"
    }
   ]
  }
 ]
}