name: cdev-demo
kind: Project
backend: aws-backend
variables:
  organization: test
  region: eu-central-1 # example
  state_bucket_name: test-cdev-state # example
  cluster_name: test # example
  domain: cluster.dev
  env: "test"
  worker_node_instance_type: "t2.medium"
  public_key_name: cdev
  public_key: "ssh-rsa example_..." # example
  argocd_server_admin_password: "$2y$10$McGTcvBMc55zY19tozf43.CmEaoO7ZESb8ea4KEa0A8b4h52EfZcS" # example
  grafana_password: "password" # example
