name: my-k3s-cluster
template: https://github.com/shalb/cdev-aws-k3s?ref=v0.3.0
kind: Stack
backend: aws-backend
variables:
  bucket: {{ .project.variables.state_bucket_name }}
  region: {{ .project.variables.region }}
  organization: {{ .project.variables.organization }}
  cluster_name: {{ .project.variables.cluster_name }}
  domain: {{ .project.variables.domain }}
  instance_type: "t3a.medium"
  k3s_version: "1.22.5+k3s1"
  # If you want to use existing VPC and subnets, uncomment the options below and set correct VPC ID and the subnets IDs.
  # Otherwise, the new VPC and subnets will be created automatically.
  # vpc_id: "vpc-*****"
  # public_subnets:
  #   - "subnet-*****"
  #   - "subnet-*****"
  env: {{ .project.variables.env }}
  azs:
    - "{{ .project.variables.region }}a"
    - "{{ .project.variables.region }}b"
  public_key: {{ .project.variables.public_key }}
  public_key_name: {{ .project.variables.public_key_name }}
  master_node_count: 1
  worker_node_groups:
    - name: "{{ .project.variables.cluster_name }}_node_pool"
      min_size: 1
      max_size: 1
      instance_type: {{ .project.variables.worker_node_instance_type }}
  argocdServerAdminPassword: {{ .project.variables.argocd_server_admin_password }}
