{
 "title": "Airflow (airflow_exporter)",
 "tags": [
  "dba",
  "operations",
  "featured"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "data_source", "label": "Data source", "query": "prometheus" },
   {
    "name": "pod_name",
    "label": "Pod",
    "query": "label_values(airflow_exporter_up, pod_name)"
   },
   {
    "name": "dag",
    "label": "Dag",
    "query": "label_values(airflow_exporter_dags_last_status, dag_id)"
   },
   {
    "name": "limit",
    "query": "1,2,3,4,5,6,7,8,9,10,15,20,25,30,40,50,70,100,9999"
   }
  ]
 },
 "panels": [
  {
   "title": "Exporter",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Airflow exporter scrape status (bottom $limit)",
     "type": "graph",
     "description": "1 = OK",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "bottomk($limit, up{job=~\".*airflow.*\",pod_name=~\"$pod_name\"})",
       "legendFormat": "{{ pod_name }}"
      }
     ]
    },
    {
     "title": "Airflow exporter collector status (bottom $limit)",
     "type": "graph",
     "description": "1 = OK",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "bottomk($limit, airflow_exporter_up{pod_name=~\"$pod_name\"})",
       "legendFormat": "{{ pod_name }}"
      }
     ]
    }
   ]
  },
  { "title": "Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Airflow services health checks status (bottom $limit)",
   "type": "graph",
   "description": "1 = OK",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "bottomk($limit, airflow_exporter_health_status{pod_name=~\"$pod_name\"})",
     "legendFormat": " {{airflow_service}}"
    }
   ]
  },
  {
   "title": "Latest scheduler heartbeat (top $limit)",
   "type": "graph",
   "description": "Latest scheduler heartbeat seconds ago.\n\nOK if < 60 seconds",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "topk($limit, time() - airflow_exporter_scheduler_seconds{pod_name=~\"$pod_name\"})",
     "legendFormat": " {{airflow_service}}"
    }
   ]
  },
  { "title": "Dags", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "DAGs last status (bottom $limit)",
   "type": "graph",
   "description": "success: 1\n\nfailed: -1\n\nrunning: -2\n\nskipped: -3\n\nqueued: -4\n\nup_for_retry: -5\n\nup_for_reschedule: -6\n\nupstream_failed: -7\n\nno_status: 0",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "bottomk($limit, airflow_exporter_dags_last_status{pod_name=~\"$pod_name\",dag_id=~\"$dag\"})",
     "legendFormat": " {{dag_id}}"
    }
   ]
  },
  {
   "title": "DAGs last run (top $limit)",
   "type": "graph",
   "description": "DAGs last run",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "topk($limit, time() - airflow_exporter_dags_last_run_seconds{pod_name=~\"$pod_name\",dag_id=~\"$dag\"})",
     "legendFormat": " {{dag_id}}"
    }
   ]
  }
 ]
}