{
 "title": "Gitlab metrics",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "data_source", "label": "Data source", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Exporter",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Metrics scrape status",
     "type": "graph",
     "description": "1 = OK",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "up{job=\"gitlab-runner\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  { "title": "Jobs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Failed jobs",
   "type": "graph",
   "description": "Number of failed jobs with 15m interval and failure reason: Runner system failure",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(gitlab_runner_failed_jobs_total{failure_reason=\"runner_system_failure\"}[15m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Failed jobs (percent)",
   "type": "graph",
   "description": "Percent of failed jobs with 15m interval and failure reason: Runner system failure",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg without(failure_reason) (delta(gitlab_runner_failed_jobs_total{failure_reason=\"runner_system_failure\"}[15m])) / delta(gitlab_runner_jobs_total[15m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "API",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "API requests (without 2xx)",
     "type": "graph",
     "description": "Number of API requests with http status (2xx excluded) for last 15m",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "delta(gitlab_runner_api_request_statuses_total{status!~\"2.*\"}[15m])",
       "legendFormat": "{{pod}} {{status}}"
      }
     ]
    }
   ]
  }
 ]
}