{
 "title": "JVM (Actuator)",
 "description": "Dashboard for Micrometer(Java, Spring Boot, Actuator)",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(jvm_memory_used_bytes, namespace)"
   },
   {
    "name": "pod_name",
    "label": "Pod name",
    "query": "label_values(jvm_memory_used_bytes{namespace=~\"$namespace\"}, pod_name)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(jvm_memory_used_bytes{pod_name=\"$pod_name\"}, instance)"
   },
   {
    "name": "jvm_memory_pool_heap",
    "label": "JVM Memory Pools Heap",
    "query": "label_values(jvm_memory_used_bytes{pod_name=\"$pod_name\", area=\"heap\"},id)"
   },
   {
    "name": "jvm_memory_pool_nonheap",
    "label": "JVM Memory Pools Non-Heap",
    "query": "label_values(jvm_memory_used_bytes{pod_name=\"$pod_name\", area=\"nonheap\"},id)"
   }
  ]
 },
 "panels": [
  { "title": "Quick Facts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "process_uptime_seconds{namespace=~\"$namespace\",pod_name=\"$pod_name\"}"
    }
   ]
  },
  {
   "title": "Start time",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 1 },
   "format": "dateTimeAsIso",
   "valueName": "current",
   "targets": [
    {
     "expr": "process_start_time_seconds{namespace=~\"$namespace\",pod_name=\"$pod_name\"}*1000"
    }
   ]
  },
  {
   "title": "Heap used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{namespace=~\"$namespace\",pod_name=\"$pod_name\", area=\"heap\"})*100/sum(jvm_memory_max_bytes{namespace=~\"$namespace\",pod_name=\"$pod_name\", area=\"heap\"})"
    }
   ]
  },
  {
   "title": "Non-Heap used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{namespace=~\"$namespace\",pod_name=\"$pod_name\", area=\"nonheap\"})*100/sum(jvm_memory_max_bytes{namespace=~\"$namespace\",pod_name=\"$pod_name\", area=\"nonheap\"})"
    }
   ]
  },
  {
   "title": "I/O Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Rate",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_seconds_count{namespace=~\"$namespace\",pod_name=\"$pod_name\"}[1m]))",
       "legendFormat": "HTTP"
      }
     ]
    },
    {
     "title": "Errors",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 5 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_seconds_count{namespace=~\"$namespace\",pod_name=\"$pod_name\", status=~\"5..\"}[1m]))",
       "legendFormat": "HTTP - 5xx"
      }
     ]
    },
    {
     "title": "Duration",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 5 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_seconds_sum{namespace=~\"$namespace\",pod_name=\"$pod_name\", status!~\"5..\"}[1m]))/sum(rate(http_server_requests_seconds_count{namespace=~\"$namespace\",pod_name=\"$pod_name\", status!~\"5..\"}[1m]))",
       "legendFormat": "HTTP - AVG"
      },
      {
       "expr": "max(http_server_requests_seconds_max{namespace=~\"$namespace\",pod_name=\"$instance\", status!~\"5..\"})",
       "legendFormat": "HTTP - MAX"
      }
     ]
    },
    {
     "title": "Utilisation",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "tomcat_threads_busy{namespace=~\"$namespace\",pod_name=\"$pod_name\"} or tomcat_threads_busy_threads{namespace=~\"$namespace\",pod_name=\"$pod_name\"}",
       "legendFormat": "TOMCAT - BSY"
      },
      {
       "expr": "tomcat_threads_current{namespace=~\"$namespace\",pod_name=\"$pod_name\"} or tomcat_threads_current_threads{namespace=~\"$namespace\",pod_name=\"$pod_name\"}",
       "legendFormat": "TOMCAT - CUR"
      },
      {
       "expr": "tomcat_threads_config_max{namespace=~\"$namespace\",pod_name=\"$pod_name\"} or tomcat_threads_config_max_threads{namespace=~\"$namespace\",pod_name=\"$instance\"}",
       "legendFormat": "TOMCAT - MAX"
      },
      {
       "expr": "jetty_threads_busy{namespace=~\"$namespace\",instance=\"$pod_name\"}",
       "legendFormat": "JETTY - BSY"
      },
      {
       "expr": "jetty_threads_current{namespace=~\"$namespace\",pod_name=\"$pod_name\"}",
       "legendFormat": "JETTY - CUR"
      },
      {
       "expr": "jetty_threads_config_max{namespace=~\"$namespace\",pod_name=\"$instance\"}",
       "legendFormat": "JETTY - MAX"
      }
     ]
    }
   ]
  },
  { "title": "JVM Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "JVM Heap",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{namespace=~\"$namespace\",pod_name=\"$pod_name\", area=\"heap\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{namespace=~\"$namespace\",pod_name=\"$instance\", area=\"heap\"})",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{namespace=~\"$namespace\",pod_name=\"$pod_name\", area=\"heap\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "JVM Non-Heap",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 6 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{namespace=~\"$namespace\",pod_name=\"$pod_name\", area=\"nonheap\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{namespace=~\"$namespace\",pod_name=\"$pod_name\", area=\"nonheap\"})",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{namespace=~\"$namespace\",pod_name=\"$pod_name\", area=\"nonheap\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "JVM Total",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{namespace=~\"$namespace\",pod_name=\"$pod_name\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{namespace=~\"$namespace\",pod_name=\"$pod_name\"})",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{namespace=~\"$namespace\",instance=\"$instance\"})",
     "legendFormat": "max"
    },
    {
     "expr": "process_memory_rss_bytes{namespace=~\"$namespace\",instance=\"$instance\"}",
     "legendFormat": "rss"
    },
    {
     "expr": "process_memory_pss_bytes{namespace=~\"$namespace\",instance=\"$instance\"}",
     "legendFormat": "pss"
    },
    {
     "expr": "process_memory_swap_bytes{namespace=~\"$namespace\",instance=\"$instance\"}",
     "legendFormat": "swap"
    },
    {
     "expr": "process_memory_swappss_bytes{namespace=~\"$namespace\",instance=\"$instance\"}",
     "legendFormat": "swappss"
    },
    {
     "expr": "process_memory_pss_bytes{namespace=~\"$namespace\",instance=\"$instance\"} + process_memory_swap_bytes{namespace=~\"$namespace\",instance=\"$instance\"}",
     "legendFormat": "phys (pss+swap)"
    }
   ]
  },
  {
   "title": "JVM Native Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 6 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "(process_memory_pss_bytes{namespace=~\"$namespace\",instance=\"$instance\"} + process_memory_swap_bytes{namespace=~\"$namespace\",instance=\"$instance\"}  - on(instance) sum(jvm_memory_committed_bytes{namespace=~\"$namespace\",instance=\"$instance\"})  by(instance)) >= 0",
     "legendFormat": "native"
    }
   ]
  },
  {
   "title": "JVM Misc",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "system_cpu_usage{namespace=~\"$namespace\",pod_name=\"$pod_name\"}",
       "legendFormat": "system"
      },
      {
       "expr": "process_cpu_usage{namespace=~\"$namespace\",pod_name=\"$pod_name\"}",
       "legendFormat": "process"
      },
      {
       "expr": "avg_over_time(process_cpu_usage{namespace=~\"$namespace\",instance=\"$instance\"}[1h])",
       "legendFormat": "process-1h"
      }
     ]
    },
    {
     "title": "Load",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "system_load_average_1m{namespace=~\"$namespace\",pod_name=\"$pod_name\"}",
       "legendFormat": "system-1m"
      },
      {},
      {
       "expr": "system_cpu_count{namespace=~\"$namespace\",pod_name=\"$pod_name\"}",
       "legendFormat": "cpu"
      }
     ]
    },
    {
     "title": "Threads",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_threads_live{pod_name=\"$pod_name\"} or jvm_threads_live_threads{pod_name=\"$pod_name\"}",
       "legendFormat": "live"
      },
      {
       "expr": "jvm_threads_daemon{pod_name=\"$pod_name\"} or jvm_threads_daemon_threads{pod_name=\"$pod_name\"}",
       "legendFormat": "daemon"
      },
      {
       "expr": "jvm_threads_peak{instance=\"$instance\"} or jvm_threads_peak_threads{instance=\"$instance\"}",
       "legendFormat": "peak"
      },
      {
       "expr": "process_threads{instance=\"$instance\"}",
       "legendFormat": "process"
      }
     ]
    },
    {
     "title": "Thread States",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_threads_states_threads{pod_name=\"$pod_name\"}",
       "legendFormat": "{{state}}"
      }
     ]
    },
    {
     "title": "Log Events (1m)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 18, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(logback_events_total{instance=\"$instance\"}[1m])",
       "legendFormat": "{{level}}"
      }
     ]
    },
    {
     "title": "File Descriptors",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "process_open_fds{instance=\"$instance\"}",
       "legendFormat": "open"
      },
      {
       "expr": "process_max_fds{instance=\"$instance\"}",
       "legendFormat": "max"
      },
      {
       "expr": "process_files_open{instance=\"$instance\"} or process_files_open_files{instance=\"$instance\"}",
       "legendFormat": "open"
      },
      {
       "expr": "process_files_max{instance=\"$instance\"} or process_files_max_files{instance=\"$instance\"}",
       "legendFormat": "max"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Memory Pools (Heap)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "repeat": "persistence_counts",
   "collapsed": true,
   "panels": [
    {
     "title": "$jvm_memory_pool_heap",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
     "repeat": "jvm_memory_pool_heap",
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{instance=\"$instance\", id=\"$jvm_memory_pool_heap\"}",
       "legendFormat": "used"
      },
      {
       "expr": "jvm_memory_committed_bytes{instance=\"$instance\", id=\"$jvm_memory_pool_heap\"}",
       "legendFormat": "commited"
      },
      {
       "expr": "jvm_memory_max_bytes{instance=\"$instance\", id=\"$jvm_memory_pool_heap\"}",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "$jvm_memory_pool_heap",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{instance=\"$instance\", id=\"$jvm_memory_pool_heap\"}",
       "legendFormat": "used"
      },
      {
       "expr": "jvm_memory_committed_bytes{instance=\"$instance\", id=\"$jvm_memory_pool_heap\"}",
       "legendFormat": "commited"
      },
      {
       "expr": "jvm_memory_max_bytes{instance=\"$instance\", id=\"$jvm_memory_pool_heap\"}",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "$jvm_memory_pool_heap",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{instance=\"$instance\", id=\"$jvm_memory_pool_heap\"}",
       "legendFormat": "used"
      },
      {
       "expr": "jvm_memory_committed_bytes{instance=\"$instance\", id=\"$jvm_memory_pool_heap\"}",
       "legendFormat": "commited"
      },
      {
       "expr": "jvm_memory_max_bytes{instance=\"$instance\", id=\"$jvm_memory_pool_heap\"}",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "$jvm_memory_pool_heap",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{instance=\"$instance\", id=\"$jvm_memory_pool_heap\"}",
       "legendFormat": "used"
      },
      {
       "expr": "jvm_memory_committed_bytes{instance=\"$instance\", id=\"$jvm_memory_pool_heap\"}",
       "legendFormat": "commited"
      },
      {
       "expr": "jvm_memory_max_bytes{instance=\"$instance\", id=\"$jvm_memory_pool_heap\"}",
       "legendFormat": "max"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Memory Pools (Non-Heap)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "$jvm_memory_pool_nonheap",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
     "repeat": "jvm_memory_pool_nonheap",
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{instance=\"$instance\", id=\"$jvm_memory_pool_nonheap\"}",
       "legendFormat": "used"
      },
      {
       "expr": "jvm_memory_committed_bytes{instance=\"$instance\", id=\"$jvm_memory_pool_nonheap\"}",
       "legendFormat": "commited"
      },
      {
       "expr": "jvm_memory_max_bytes{instance=\"$instance\", id=\"$jvm_memory_pool_nonheap\"}",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "$jvm_memory_pool_nonheap",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 9 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{instance=\"$instance\", id=\"$jvm_memory_pool_nonheap\"}",
       "legendFormat": "used"
      },
      {
       "expr": "jvm_memory_committed_bytes{instance=\"$instance\", id=\"$jvm_memory_pool_nonheap\"}",
       "legendFormat": "commited"
      },
      {
       "expr": "jvm_memory_max_bytes{instance=\"$instance\", id=\"$jvm_memory_pool_nonheap\"}",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "$jvm_memory_pool_nonheap",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 9 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{instance=\"$instance\", id=\"$jvm_memory_pool_nonheap\"}",
       "legendFormat": "used"
      },
      {
       "expr": "jvm_memory_committed_bytes{instance=\"$instance\", id=\"$jvm_memory_pool_nonheap\"}",
       "legendFormat": "commited"
      },
      {
       "expr": "jvm_memory_max_bytes{instance=\"$instance\", id=\"$jvm_memory_pool_nonheap\"}",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "$jvm_memory_pool_nonheap",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{instance=\"$instance\", id=\"$jvm_memory_pool_nonheap\"}",
       "legendFormat": "used"
      },
      {
       "expr": "jvm_memory_committed_bytes{instance=\"$instance\", id=\"$jvm_memory_pool_nonheap\"}",
       "legendFormat": "commited"
      },
      {
       "expr": "jvm_memory_max_bytes{instance=\"$instance\", id=\"$jvm_memory_pool_nonheap\"}",
       "legendFormat": "max"
      }
     ]
    }
   ]
  },
  {
   "title": "Garbage Collection",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Collections",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "rate(jvm_gc_pause_seconds_count{instance=\"$instance\"}[1m])",
       "legendFormat": "{{action}} ({{cause}})"
      }
     ]
    },
    {
     "title": "Pause Durations",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 17 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(jvm_gc_pause_seconds_sum{instance=\"$instance\"}[1m])/rate(jvm_gc_pause_seconds_count{instance=\"$instance\"}[1m])",
       "legendFormat": "avg {{action}} ({{cause}})"
      },
      {
       "expr": "jvm_gc_pause_seconds_max{instance=\"$instance\"}",
       "legendFormat": "max {{action}} ({{cause}})"
      }
     ]
    },
    {
     "title": "Allocated/Promoted",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 17 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "rate(jvm_gc_memory_allocated_bytes_total{instance=\"$instance\"}[1m])",
       "legendFormat": "allocated"
      },
      {
       "expr": "rate(jvm_gc_memory_promoted_bytes_total{instance=\"$instance\"}[1m])",
       "legendFormat": "promoted"
      }
     ]
    }
   ]
  },
  {
   "title": "Classloading",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Classes loaded",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_classes_loaded{instance=\"$instance\"} or jvm_classes_loaded_classes{instance=\"$instance\"}",
       "legendFormat": "loaded"
      }
     ]
    },
    {
     "title": "Class delta (5m)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "delta(jvm_classes_loaded{application=\"$application\",instance=\"$instance\"}[5m]) or delta(jvm_classes_loaded_classes{application=\"$application\",instance=\"$instance\"}[5m])",
       "legendFormat": "delta"
      }
     ]
    }
   ]
  },
  {
   "title": "Buffer Pools",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Direct Buffers",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_buffer_memory_used_bytes{instance=\"$instance\", id=\"direct\"}",
       "legendFormat": "used"
      },
      {
       "expr": "jvm_buffer_total_capacity_bytes{instance=\"$instance\", id=\"direct\"}",
       "legendFormat": "capacity"
      }
     ]
    },
    {
     "title": "Direct Buffers",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_buffer_count{instance=\"$instance\", id=\"direct\"} or jvm_buffer_count_buffers{instance=\"$instance\", id=\"direct\"}",
       "legendFormat": "count"
      }
     ]
    },
    {
     "title": "Mapped Buffers",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_buffer_memory_used_bytes{instance=\"$instance\", id=\"mapped\"}",
       "legendFormat": "used"
      },
      {
       "expr": "jvm_buffer_total_capacity_bytes{instance=\"$instance\", id=\"mapped\"}",
       "legendFormat": "capacity"
      }
     ]
    },
    {
     "title": "Mapped Buffers",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_buffer_count{instance=\"$instance\", id=\"mapped\"} or jvm_buffer_count_buffers{instance=\"$instance\", id=\"mapped\"}",
       "legendFormat": "count"
      }
     ]
    }
   ]
  }
 ]
}