{
 "title": "Redis (redis_exporter)",
 "description": "Redis Dashboard for Prometheus Redis Exporter 1.x",
 "tags": [
  "prometheus",
  "redis"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "Datasource", "label": "datasource", "query": "prometheus" },
   { "name": "host", "label": "Host", "query": { "query": "label_values(redis_up, pod)" } }
  ]
 },
 "panels": [
  {
   "title": "System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Uptime",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "redis_uptime_in_seconds{pod=~\"$host\"}",
       "legendFormat": "{{ pod }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Usage",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "redis_memory_used_bytes{pod=~\"$host\"}",
       "legendFormat": "{{ pod }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network I/O",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "rate(redis_net_input_bytes_total{pod=~\"$host\"}[5m])",
       "legendFormat": "input {{ pod }}"
      },
      {
       "expr": "rate(redis_net_output_bytes_total{pod=~\"$host\"}[5m])",
       "legendFormat": "output {{ pod }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Connections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Connected Clients",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "redis_connected_clients{pod=~\"$host\"}",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "Blocked Clients",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "redis_blocked_clients{pod=~\"$host\"}",
       "legendFormat": "{{ pod }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Database",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Items per DB",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(redis_db_keys{pod=~\"$host\"}) by (db, pod)",
       "legendFormat": "{{ db }} {{ pod }}"
      }
     ]
    }
   ]
  },
  { "title": "Keys", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Not-Expiring Keys",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (redis_db_keys{pod=~\"$host\"}) by (pod) - sum (redis_db_keys_expiring{pod=~\"$host\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Expiring Keys",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (redis_db_keys_expiring{pod=~\"$host\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Expired Keys per second",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(redis_expired_keys_total{pod=~\"$host\"}[5m])) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Evicted Keys per second",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(redis_evicted_keys_total{pod=~\"$host\"}[5m])) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Commands",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Commands / sec",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(redis_commands_total{pod=~\"$host\"} [1m])) by (cmd, pod)",
       "legendFormat": "{{ cmd }} {{ pod }}"
      }
     ]
    },
    {
     "title": "Hits per Sec",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "irate(redis_keyspace_hits_total{pod=~\"$host\"}[5m])",
       "legendFormat": "{{ pod }}"
      },
      {
       "expr": "irate(redis_keyspace_misses_total{instance=~\"$instance\"}[5m])",
       "legendFormat": "misses, {{ instance }}"
      }
     ]
    },
    {
     "title": "Total Time Spent by Command / sec",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(irate(redis_commands_duration_seconds_total{pod=~\"$host\"}[1m])) by (cmd, pod) != 0",
       "legendFormat": "{{ cmd }} {{ pod }}"
      }
     ]
    },
    {
     "title": "Average Time Spent by Command / sec",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(irate(redis_commands_duration_seconds_total{pod=~\"$host\"}[1m])) by (cmd, pod)\n  /\nsum(irate(redis_commands_total{pod=~\"$host\"}[1m])) by (cmd, pod)\n",
       "legendFormat": "{{ cmd }} {{ pod }}"
      }
     ]
    }
   ]
  }
 ]
}